name: haskell-pong-game
version: 0.0.0.1
license: BSD3
author: "FMI IS 2024/2025"

dependencies:
  - base >= 4.14 && < 5
  - gloss

library:
  source-dirs: src

executables:
  haskell-pong-game:
    main: Main.hs
    source-dirs: [app, src]
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
